project:
  type: website
  output-dir: "_site"

website:
  title: "Spørsmål til Skole-Norge"
  description: "Analyser og resultater fra Utdanningsdirektoratets spørreundersøkelse i forbindelse med evalueringen av fagfornyelsen"
  navbar:
    logo: "https://www.nifu.no/wp-content/uploads/logo_hvit.png"
    left:
      - file: "Main/om_prosjektet.qmd"
      - file: "Main/om_metode.qmd"
      - sidebar:Rapporter
      - file: "Main/tidligere_rapporter.qmd"
      # - sidebar:tidsserier
  sidebar:
    - id: Rapporter
      title: "Rapporter"
      contents: "Rapporter"
    # - id: tidsserier
    #   title: "Tidsserier"
    #   contents: "tidsserier"

execute:
  freeze: true
  cache: true

metadata-files:
  - _nifu_global.yaml # Must be in same folder/subfolder
